lib/javelin: manage (or not) external network
* If external network is managed by Spinal Stack, we ensure it exists
* If external network is managed by Spinal Stack, we configure Javelin
  resource YAML file to use this floating IP network name for servers
* If external network is not manage by Spinal Stack, we still support
  Javelin, without servers though.

diff --git a/tempest/lib/javelin b/tempest/lib/javelin
--- a/tempest/lib/javelin
+++ b/tempest/lib/javelin
@@ -21,112 +21,26 @@ else
   JAVELIN_CMD="python /usr/share/openstack-tempest-juno/tempest/cmd/javelin.py"
 fi
 
-public_net_name=$(/usr/bin/extract.py config.floating_network_name /etc/config-tools/global.yml)
+# public_net_name is optional, so we don't want to fail extract.py command.
+public_net_name=$(/usr/bin/extract.py config.floating_network_name /etc/config-tools/global.yml || true)
 
 javelin_get_or_create_resourcefile () {
+    # Javelin resource file does not exist, we create it
     if [ ! -r "$resourcefile" ]; then
-	cat > "$resourcefile" <<EOF
-# This is a yaml description for the most basic definitions
-# of what should exist across the resource boundary. Perhaps
-# one day this will grow into a Heat resource template, but as
-# Heat isn't a known working element in the upgrades, we do
-# this much simpler thing for now.
-
-tenants:
-  - javelin
-  - discuss
-
-users:
-  - name: javelin
-    pass: gungnir
-    tenant: javelin
-  - name: javelin2
-    pass: gungnir2
-    tenant: discuss
-
-secgroups:
-  - name: angon
-    owner: javelin
-    description: angon
-    rules:
-      - 'icmp -1 -1 0.0.0.0/0'
-      - 'tcp 22 22 0.0.0.0/0'
-  - name: baobab
-    owner: javelin
-    description: baobab
-    rules:
-      - 'tcp 80 80 0.0.0.0/0'
-
-# resources that we want to create
-images:
-  - name: javelin_cirros
-    owner: javelin
-    imgdir: images
-    file: cirros-0.3.2-x86_64-blank.img
-    format: ami
-    aki: cirros-0.3.2-x86_64-vmlinuz
-    ari: cirros-0.3.2-x86_64-initrd
-volumes:
-  - name: assegai
-    server: peltast
-    owner: javelin
-    gb: 1
-    device: /dev/vdb
-  - name: pifpouf
-    server: hoplite
-    owner: javelin
-    gb: 2
-    device: /dev/vdb
-networks:
-  - name: world1
-    owner: javelin
-  - name: world2
-    owner: javelin
-subnets:
-  - name: subnet1
-    range: 10.1.0.0/24
-    network: world1
-    owner: javelin
-  - name: subnet2
-    range: 192.168.1.0/24
-    network: world2
-    owner: javelin
-routers:
-  - name: connector
-    owner: javelin
-    gateway: true
-    subnet:
-      - subnet1
-      - subnet2
-servers:
-  - name: peltast
-    owner: javelin
-    flavor: m1.small
-    image: javelin_cirros
-    networks:
-      - world1
-    secgroups:
-      - angon
-      - baobab
-    floating_ip_pool: $public_net_name
-  - name: hoplite
-    owner: javelin
-    flavor: m1.medium
-    image: javelin_cirros
-    networks:
-      - world2
-    secgroups:
-      - angon
-    floating_ip_pool: $public_net_name
-objects:
-  - container: jc1
-    name: javelin1
-    owner: javelin
-    file: /etc/hosts
-telemetry: true
-EOF
+        # if we manage external network
+        if [ ! -z "$public_net_name" ]; then
+            cp ../javelin-with-external-network.yaml $resourcefile
+            sed -i "s/fakepublicnetwork/$public_net_name/g" $resourcefile
+            # we ensure external network exist
+            if ! neutron net-list | grep $public_net_name; then
+                neutron net-create  --shared $public_net_name -- --router:external=True
+                neutron subnet-create $public_net_name --allocation-pool start=$floating_network_start,end=$floating_network_end --gateway=$floating_network_gateway --enable_dhcp=False $floating_network_subnet
+            fi
+        # otherwise we don't manage external network
+        else
+            cp ../javelin-without-external-network.yaml $resourcefile
+        fi
     fi
-
     echo "$resourcefile"
 }
 
